=== bertcarnell/USS-Saufely-DD-465/docs/saufley_reunion_photos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <!-- Copyright 2022 Robert Carnell -->
    <xsd:element name="dataroot">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="photo" minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="photo">
        <xsd:complexType mixed="true">
            <xsd:all>
                <xsd:element name="url" minOccurs="1" maxOccurs="1" type="xsd:string"/>
                <xsd:element name="date" minOccurs="1" maxOccurs="1" type="xsd:string"/>
                <xsd:element name="location" minOccurs="1" maxOccurs="1" type="xsd:string"/>
                <xsd:element name="pictured" minOccurs="1" maxOccurs="1" type="xsd:string"/>
                <xsd:element name="source" minOccurs="1" maxOccurs="1" type="xsd:string"/>
            </xsd:all>
            <xsd:attribute name="id" type="xsd:int"/>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== bertcarnell/USS-Saufely-DD-465/docs/saufley_reunion_photos.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="saufley_reunion_photos.xsl"?>
<dataroot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="saufley_reunion_photos.xsd">
<!-- Copyright 2022 Robert Carnell -->

<photo id="81">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/moviephotos/vlcsnap-2022-04-03-16h26m01s514.png</url>
    <date>1954</date>
    <location>South Bend, IN</location>
    <pictured>(L to R) Hillman, Rogers, Curry, Bogard, Burger, Wittington</pictured>
    <source>USS Saufley Reunions CD - Maggie Downie, Uncommon Crew pg 92</source>
</photo>
<photo id="82">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/moviephotos/vlcsnap-2022-04-03-16h25m25s738.png</url>
    <date>1955</date>
    <location>Dayton, OH</location>
    <pictured>(L to R) Curry, Hayes, Rogers, Hillman, Burger</pictured>
    <source>USS Saufley Reunions CD - Maggie Downie, Uncommon Crew pg 92</source>
</photo>
<photo id="83">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/moviephotos/vlcsnap-2022-04-03-16h25m33s904.png</url>
    <date>1956</date>
    <location>Chicago, IL</location>
    <pictured>(L to R, Back) Roger, Hillman, Fagan, Whittington, Newby, (Front) DeGuiseppe, Burger, Hayes</pictured>
    <source>USS Saufley Reunions CD - Maggie Downie, Uncommon Crew pg 93</source>
</photo>
<photo id="84">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/moviephotos/vlcsnap-2022-04-03-16h25m41s291.png</url>
    <date>1957</date>
    <location>Litchfield, IL</location>
    <pictured>(L to R) (Back) Whittington, Cromie, Fagan, Ernest Lee, Hillman, LT John Rogers, LT Andy Taaffe (Front) DeGuiseppe, Doc Fore, Hayes, Polesak</pictured>
    <source>USS Saufley Reunions CD - Maggie Downie, Uncommon Crew pg 93</source>
</photo>
<photo id="85">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/moviephotos/vlcsnap-2022-04-03-16h27m04s427.png</url>
    <date>1964</date>
    <location>Norwalk, CT</location>
    <pictured>(L to R) (Back) Cromie, Larned, Melia, Dalland, Rogers, Einhorn, Burger (Center) Hillman, Fagan, Polesak, CAPT Brown, Frank Devine, Ed Duffy, Wilson, DePalma, (Front) DeGuiseppi, Curtin, ??, ??, ??, Dorian, Cyr, Czechowski, Condon, Braddick, (Bottom) Heyne</pictured>
    <source>USS Saufley Reunions CD - Maggie Downie, Uncommon Crew pg 95</source>
</photo>
<photo id="87">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/reunionphotos/AltonBayNH1965_20230903_15555041_0200.jpg</url>
    <date>1965</date>
    <location>Alton Bay, NH</location>
    <pictured></pictured>
    <source>Robert Rettgers Personal Photos</source>
</photo>
<photo id="88">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/reunionphotos/AltonBayNH1965_20230903_15561480_0201.jpg</url>
    <date>1965</date>
    <location>Alton Bay, NH</location>
    <pictured></pictured>
    <source>Robert Rettgers Personal Photos</source>
</photo>
<photo id="89">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/reunionphotos/AltonBayNH1965_20230903_15581799_0205.jpg</url>
    <date>1965</date>
    <location>Alton Bay, NH</location>
    <pictured></pictured>
    <source>Robert Rettgers Personal Photos</source>
</photo>
<photo id="86">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/moviephotos/vlcsnap-2022-04-03-16h27m27s347.png</url>
    <date>1966</date>
    <location>Sylva, NC</location>
    <pictured>(L to R, Back) Day, Newby, Rogers, Veach, Klingensmith, Spagel, Powell, CAPT Brown, Fagan, Watts, Hillman Zimmerman, (Front) Cromie, Polesak, Cyr, Elliott, Parker, Devine</pictured>
    <source>USS Saufley Reunions CD - Maggie Downie, Uncommon Crew pg 95</source>
</photo>
<photo id="65">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/moviephotos/vlcsnap-2022-04-03-16h26m48s420.png</url>
    <date>1960s</date>
    <location></location>
    <pictured></pictured>
    <source>USS Saufley Reunions CD - Maggie Downie</source>
</photo>
<photo id="68">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/moviephotos/vlcsnap-2022-04-03-16h27m43s481.png</url>
    <date>1971</date>
    <location>Wolcott, CT</location>
    <pictured>(Third above sign) Robert Rettgers, (standing right) John Larned</pictured>
    <source>Robert Rettgers Personal Photos, USS Saufley Reunions CD - Maggie Downie</source>
</photo>
<photo id="90">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/reunionphotos/WolcottCN1971_20230903_16031803_0217.jpg</url>
    <date>1971</date>
    <location>Wolcott, CT</location>
    <pictured>(Third above sign) Robert Rettgers, (standing right) John Larned</pictured>
    <source>Robert Rettgers Personal Photos</source>
</photo>
<photo id="69">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/moviephotos/vlcsnap-2022-04-03-16h28m36s695.png</url>
    <date>1970s</date>
    <location></location>
    <pictured></pictured>
    <source>USS Saufley Reunions CD - Maggie Downie</source>
</photo>
<photo id="71">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/moviephotos/vlcsnap-2022-04-03-16h30m35s118.png</url>
    <date>1970, 1973, 1974, or 1977</date>
    <location></location>
    <pictured>(Standing center blue and yellow shirt) Robert Rettgers</pictured>
    <source>USS Saufley Reunions CD - Maggie Downie</source>
</photo>
<photo id="72">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/moviephotos/vlcsnap-2022-04-03-16h31m38s940.png</url>
    <date>1970s</date>
    <location></location>
    <pictured></pictured>
    <source>USS Saufley Reunions CD - Maggie Downie</source>
</photo>
<photo id="70">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/moviephotos/vlcsnap-2022-04-03-16h29m07s304.png</url>
    <date>1970, 1973, 1974, or 1977</date>
    <location></location>
    <pictured>(Standing Navy Blue shirt) Robert Rettgers</pictured>
    <source>USS Saufley Reunions CD - Maggie Downie</source>
</photo>
<photo id="1">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/reunionphotos/Photo_2022-04-04_212031_Pre1978.jpg</url>
    <date>1970, 1973, 1974, or 1977</date>
    <location></location>
    <pictured>(L to R) Robert Rettgers, John Larned</pictured>
    <source>Robert Rettgers Personal Photos</source>
</photo>
<photo id="2">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/reunionphotos/Photo_2022-04-04_212304_Pre1978.jpg</url>
    <date>1970, 1973, 1974, or 1977</date>
    <location></location>
    <pictured>(L to R) Robert Rettgers, John Larned</pictured>
    <source>Robert Rettgers Personal Photos</source>
</photo>
<photo id="3">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/reunionphotos/Reunion_20220404_22274312.jpg</url>
    <date>3 Sep 1979</date>
    <location>Rumford, RI</location>
    <pictured>(Standing L to R) Lymon, Unknown, Robert Rettgers, E. Foss, Carl Braddick, VI Veach (Front L to R) John Larned, R Docking, Art Cyr</pictured>
    <source>Robert Rettgers Personal Photos</source>
</photo>
<photo id="4">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/reunionphotos/Reunion_20220404_22292801.jpg</url>
    <date>3 Sep 1979</date>
    <location>Rumford, RI</location>
    <pictured>(4th in from right standing) Robert Rettgers</pictured>
    <source>Robert Rettgers Personal Photos</source>
</photo>
<photo id="5">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/reunionphotos/Reunion_20220404_22295553.jpg</url>
    <date>3 Sep 1979</date>
    <location>Rumford, RI</location>
    <pictured></pictured>
    <source>Robert Rettgers Personal Photos</source>
</photo>
<photo id="6">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/reunionphotos/Reunion_20220404_22301922.jpg</url>
    <date>3 Sep 1979</date>
    <location>Rumford, RI</location>
    <pictured>(Far Right, standing) Robert Rettgers</pictured>
    <source>Robert Rettgers Personal Photos</source>
</photo>
<photo id="73">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/moviephotos/vlcsnap-2022-04-03-16h32m58s447.png</url>
    <date>1980s</date>
    <location></location>
    <pictured></pictured>
    <source>USS Saufley Reunions CD - Maggie Downie</source>
</photo>
<photo id="74">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/moviephotos/vlcsnap-2022-04-03-16h33m46s664.png</url>
    <date>1980s</date>
    <location></location>
    <pictured></pictured>
    <source>USS Saufley Reunions CD - Maggie Downie</source>
</photo>
<photo id="75">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/moviephotos/vlcsnap-2022-04-03-16h34m03s411.png</url>
    <date>1980s</date>
    <location></location>
    <pictured>(standing right) Robert Rettgers</pictured>
    <source>USS Saufley Reunions CD - Maggie Downie</source>
</photo>
<photo id="7">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/reunionphotos/Reunion_20220404_22303871.jpg</url>
    <date>1 Sep 1985</date>
    <location>Independence, MO</location>
    <pictured>(kneeling 2nd in from right) Robert Rettgers</pictured>
    <source>Robert Rettgers Personal Photos</source>
</photo>
<photo id="8">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/reunionphotos/Reunion_20220404_22305732.jpg</url>
    <date>1 Sep 1985</date>
    <location>Independence, MO</location>
    <pictured>(standing 4th in from left) Robert Rettgers</pictured>
    <source>Robert Rettgers Personal Photos</source>
</photo>
<photo id="9">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/reunionphotos/Reunion_20220404_22334296.jpg</url>
    <date>1 Sep 1985</date>
    <location>Independence, MO</location>
    <pictured>(kneeling 3rd in from right) Robert Rettgers</pictured>
    <source>Robert Rettgers Personal Photos</source>
</photo>
<photo id="10">
    <url>https://saufleyphotos.s3.us-east-2.amazonaws.com/reunionphotos/Reunion_20220404_22342597.jpg</url>
    <date>1 Sep 1985</date>
    <location>Independence, MO</location>
    <pictured>(Standing L to R) Robert Rettgers, John Larned</pictured>
